# env = KEY,VAL

env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = GTK_THEME,Materia:dark
env = QT_QPA_PLATFORMTHEME,qt6ct
env = QT_QPA_PLATFORM,wayland

evn = GTK_IM_MODULE=ibus
env = GTK_INPUT_MODULE=ibus