source = ~/.config/hypr/source/0_enviroment.conf



$terminal    = alacritty
$fileManager = thunar
$menu        = hyprlauncher

# hyprpicker
$pick1       = hyprpicker -f rgb -a -s 1.0 -u 64 -d -o "{0} {1} {2}"
$pick2       = hyprpicker -a -s 1.0 -u 64

# grimblast
$screenshot1 = grimblast -n save screen ~/Pictures/$(date +%+4Y%m%d-%H%M%S-screen.png)
$screenshot2 = grimblast -n -f save area ~/Pictures/$(date +%+4Y%m%d-%H%M%S-area.png)
