source = ~/.config/hypr/source/3_binds.conf




# windowrule = suppress_event maximize, match:class [.]*

windowrule = float 1,        match:title (Open File|Open Folder|Save File|Save As|Rename .*|Choose .*)
windowrule = stay_focused 1, match:title (Open File|Open Folder|Save File|Save As|Rename .*|Choose .*)
