const themes = {
    default_light: {
        "--font-family-head":        "Noto Sans",
        "--font-family-text":        "Noto Sans",
        "--font-family-serif":       "Bitter",
        "--font-family-code":        "JetBrains Mono",
        "--font-family-symbols":     "Symbols NerdFont Mono",

        "--size-header":             "3rem",
        "--size-side":               "20rem",
        "--size-main":               "60rem",

        "--color-fore-head-1":       "oklch( 20%   0   0)",
        "--color-fore-head-2":       "oklch( 32%   0   0)",
        "--color-fore-head-3":       "oklch( 28%   0   0)",
        "--color-fore-head-4":       "oklch( 24%   0   0)",
        "--color-fore-text":         "oklch( 20%   0   0)",
        "--color-fore-meta":         "oklch( 88%   0   0)",
        "--color-fore-meta_h":       "oklch( 80%   0   0)",
        "--color-fore-meta_a":       "oklch( 60%   0   0)",
        "--color-fore-code":         "oklch( 28%   0   0)",
        "--color-fore-code-name":    "oklch( 20%   0   0)",
        "--color-fore-code-type":    "oklch( 80%   0   0)",
        "--color-fore-code-line":    "oklch( 64%   0   0)",
        "--color-fore-code-env":     "oklch(  0%   0   0)",
        "--color-fore-code-copy":    "oklch(100%   0   0)",
        "--color-fore-table-head":   "oklch(  0%   0   0)",
        "--color-fore-table-body":   "oklch( 20%   0   0)",

        "--color-syntax-keyword":    "oklch( 28% 90%  10)",
        "--color-syntax-value":      "oklch( 28% 90% 220)",
        "--color-syntax-string":     "oklch( 56% 90% 110)",
        "--color-syntax-path":       "oklch( 56% 90% 110)",
        "--color-syntax-file":       "oklch( 56% 90% 120)",
        "--color-syntax-operator":   "oklch( 56% 90% 170)",
        "--color-syntax-flag":       "oklch( 28% 90% -30)",
        "--color-syntax-comment":    "oklch( 56%   0   0)",

        "--color-back-head":         "oklch(100%   0   0)",
        "--color-back-html":         "oklch( 92%   0   0)",
        "--color-back-side":         "oklch( 92%   0   0)",
        "--color-back-main":         "oklch( 92%   0   0)",
        "--color-back-block":        "oklch( 94%   0   0)",
        "--color-back-code-head":    "oklch( 98%   0   0)",
        "--color-back-code-body":    "oklch( 96%   0   0)",
        "--color-back-code-copy":    "oklch( 96%   0   0)",
        "--color-back-code-copy_h":  "oklch( 96%   0   0)",
        "--color-back-code-copy_a":  "oklch( 96%   0   0)",
        "--color-back-table-head":   "oklch( 98%   0   0)",
        "--color-back-table-body":   "oklch( 96%   0   0)",
        "--color-back-table-none":   "oklch( 92%   0   0)",

        "--color-border-head":       "oklch( 88%   0   0)",
        "--color-border-block":      "oklch( 88%   0   0)",
        "--color-border-code":       "oklch( 84%   0   0)",
        "--color-border-table":      "oklch( 84%   0   0)"
    },
    contrast_dark: {
        "--font-family-head":        "Noto Sans",
        "--font-family-text":        "Noto Sans",
        "--font-family-serif":       "Bitter",
        "--font-family-code":        "JetBrains Mono",
        "--font-family-symbols":     "Symbols NerdFont Mono",

        "--size-header":             "3rem",
        "--size-side":               "20rem",
        "--size-main":               "60rem",

        "--color-fore-head-1":       "oklch(100%   0   0)",
        "--color-fore-head-2":       "oklch(100%   0   0)",
        "--color-fore-head-3":       "oklch(100%   0   0)",
        "--color-fore-head-4":       "oklch(100%   0   0)",
        "--color-fore-text":         "oklch(100%   0   0)",
        "--color-fore-meta":         "oklch(100%   0   0)",
        "--color-fore-meta_h":       "oklch( 80% 80%  60)",
        "--color-fore-meta_a":       "oklch( 80% 80% 240)",
        "--color-fore-code":         "oklch(100%   0   0)",
        "--color-fore-code-name":    "oklch(100%   0   0)",
        "--color-fore-code-type":    "oklch(100%   0   0)",
        "--color-fore-code-line":    "oklch(100%   0   0)",
        "--color-fore-code-env":     "oklch(100%   0   0)",
        "--color-fore-code-copy":    "oklch(100%   0   0)",
        "--color-fore-table-head":   "oklch(100%   0   0)",
        "--color-fore-table-body":   "oklch(100%   0   0)",

        "--color-syntax-keyword":    "oklch( 80% 60%  10)",
        "--color-syntax-value":      "oklch( 80% 60% 150)",
        "--color-syntax-string":     "oklch( 80% 60% 100)",
        "--color-syntax-path":       "oklch( 80% 60% 100)",
        "--color-syntax-file":       "oklch( 80% 80%  70)",
        "--color-syntax-operator":   "oklch( 80% 60% 240)",
        "--color-syntax-flag":       "oklch( 80% 60% -60)",
        "--color-syntax-comment":    "oklch( 80%   0   0)",

        "--color-back-head":         "oklch(  0%   0   0)",
        "--color-back-html":         "oklch(  0%   0   0)",
        "--color-back-side":         "oklch(  0%   0   0)",
        "--color-back-main":         "oklch(  0%   0   0)",
        "--color-back-block":        "oklch(  0%   0   0)",
        "--color-back-code-head":    "oklch(  0%   0   0)",
        "--color-back-code-body":    "oklch(  0%   0   0)",
        "--color-back-code-copy":    "oklch(  0%   0   0)",
        "--color-back-code-copy_h":  "oklch( 80% 60%  40)",
        "--color-back-code-copy_a":  "oklch( 80% 60% 240)",
        "--color-back-table-head":   "oklch(  0%   0   0)",
        "--color-back-table-body":   "oklch(  0%   0   0)",
        "--color-back-table-none":   "oklch(  0%   0   0)",

        "--color-border-head":       "oklch(100%   0   0)",
        "--color-border-block":      "oklch(100%   0   0)",
        "--color-border-code":       "oklch(100%   0   0)",
        "--color-border-table":      "oklch(100%   0   0)"
    }
};